#!/usr/bin/env bash

# Parent directory of this file
_DIR_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Read venv name from file
VENV_NAME=$(head -n 1 ${_DIR_PATH}/venv_name.txt | cut -f2 -d ' ')

DATA_URL="http://www.commsp.ee.ic.ac.uk/~csp-mandic/media/data/2019-04-18_INNS-2019/"

BINDER_BUILD=1

### Parse arguments
for arg in "$@"; do
    case ${arg} in
        --local-build)
            BINDER_BUILD=0
            ;;
        *)
            # Skip unknown option
            ;;
    esac
    shift
done


# Construct path to 'setup.py' of local utils and
# specify path where to download data
LOCAL_UTILS_NAME="inns"
LOCAL_UTILS_SRC=${_DIR_PATH}/${LOCAL_UTILS_NAME}
DATA_HOME=${LOCAL_UTILS_SRC}/${LOCAL_UTILS_NAME}/"data"

# Install utils for INNS 2019 tutorial in editable mode
# so that is kept with 'data'
pip install -e ${LOCAL_UTILS_SRC}

# Install kernel for consistency with local installations
python -m ipykernel install --user --name ${VENV_NAME} --display-name ${VENV_NAME}

# Get data from csp-mandic
wget -q -r -np -nd -R "index.html*" -P ${DATA_HOME} ${DATA_URL}

# Install jupyterlab extensions if executed during binder build
if [[ ($BINDER_BUILD == 1) ]]; then
    pip install jupyterlab==0.35.3
    jupyter labextension install @jupyterlab/toc --no-build
    jupyter lab clean
    jupyter lab build
fi
